#!/usr/bin/env bash
# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2026 Jan Green Larsen <jgl@laces.dk>
#
# HyperVision ISE Portal — First-boot setup wizard
#
# Runs automatically on first boot of the OVA image via first-boot.service.
# Configures hostname, static IP, gateway, DNS and root password,
# then downloads and runs install.sh from GitHub.

set -euo pipefail
export PATH="$PATH:/usr/sbin:/usr/local/sbin"

FLAGFILE="/etc/hypervision-firstboot-done"
INSTALL_URL="https://raw.githubusercontent.com/Jangreenlarsen/ise-endpoint-portal/main/install.sh"
WIZARD_VERSION="5.5.0 build 0413"

[[ -f "$FLAGFILE" ]] && exit 0

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; BLUE='\033[0;34m'; NC='\033[0m'
info()  { echo -e "${BLUE}[INFO]${NC}  $*"; }
ok()    { echo -e "${GREEN}[OK]${NC}    $*"; }
warn()  { echo -e "${YELLOW}[WARN]${NC}  $*"; }
error() { echo -e "${RED}[ERROR]${NC} $*"; exit 1; }

ask() {
    local __var=$1 __prompt=$2 __default=${3:-}
    local __val=""
    if [[ -n "$__default" ]]; then
        read -rp "$__prompt [$__default]: " __val </dev/tty
        __val="${__val:-$__default}"
    else
        while [[ -z "$__val" ]]; do
            read -rp "$__prompt: " __val </dev/tty
            [[ -z "$__val" ]] && echo "  (field is required)"
        done
    fi
    printf -v "$__var" '%s' "$__val"
}

clear
echo ""
echo "╔══════════════════════════════════════════════════════════════╗"
echo "║     HyperVision ISE Portal — First Boot Setup               ║"
echo "║     © 2026 Jan Green Larsen <hypervision@laces.dk>          ║"
printf "║     Wizard version: %-40s║\n" "$WIZARD_VERSION"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""
echo "  This wizard configures networking and installs the portal."
echo "  You will need: static IP address, subnet mask, gateway and DNS."
echo ""

# ── Hostname ──────────────────────────────────────────────────────────────────
ask HOSTNAME "Hostname" "hypervision"
hostnamectl set-hostname "$HOSTNAME"
if ! grep -q "127.0.1.1" /etc/hosts; then
    echo "127.0.1.1 $HOSTNAME" >> /etc/hosts
else
    sed -i "s/^127\.0\.1\.1.*/127.0.1.1 $HOSTNAME/" /etc/hosts
fi
ok "Hostname: $HOSTNAME"
echo ""

# ── Network interface ─────────────────────────────────────────────────────────
IFACE=$(ip -o link show | awk -F': ' '$2 != "lo" {print $2; exit}')
info "Network interface detected: $IFACE"
echo ""

# ── Network configuration ─────────────────────────────────────────────────────
ask IP_ADDR   "IP address       (e.g. 192.168.1.100)"
ask NETMASK   "Subnet mask      (e.g. 255.255.255.0)" "255.255.255.0"
ask GATEWAY   "Gateway          (e.g. 192.168.1.1)"
ask DNS1      "Primary DNS      (e.g. 8.8.8.8)"
read -rp "Secondary DNS    (Enter to skip): " DNS2 </dev/tty || DNS2=""

echo ""
echo "  ┌─ Network summary ────────────────────────────────────────┐"
printf  "  │  Interface : %-43s│\n" "$IFACE"
printf  "  │  IP address: %-43s│\n" "$IP_ADDR"
printf  "  │  Subnet    : %-43s│\n" "$NETMASK"
printf  "  │  Gateway   : %-43s│\n" "$GATEWAY"
printf  "  │  DNS       : %-43s│\n" "$DNS1${DNS2:+, $DNS2}"
echo "  └──────────────────────────────────────────────────────────┘"
echo ""
read -rp "Is the above correct? [Y/n] " CONFIRM </dev/tty
if [[ "$CONFIRM" =~ ^[nN]$ ]]; then
    warn "Aborted — run again: bash /usr/local/sbin/hypervision-firstboot.sh"
    exit 1
fi

# Write /etc/network/interfaces
cat > /etc/network/interfaces <<EOF
# Generated by HyperVision first-boot — $(date '+%Y-%m-%d %H:%M')
source /etc/network/interfaces.d/*

auto lo
iface lo inet loopback

auto $IFACE
iface $IFACE inet static
    address $IP_ADDR
    netmask $NETMASK
    gateway $GATEWAY
EOF

# DNS
{
    echo "nameserver $DNS1"
    [[ -n "$DNS2" ]] && echo "nameserver $DNS2"
} > /etc/resolv.conf

ok "Network configuration written"

# ── Root password ─────────────────────────────────────────────────────────────
echo ""
info "Set root password:"
passwd root </dev/tty
echo ""

# ── Apply network configuration ───────────────────────────────────────────────
info "Applying network configuration..."

# Stop any DHCP clients
pkill dhclient 2>/dev/null || true
pkill dhcpcd  2>/dev/null || true
sleep 1

systemctl restart networking
sleep 2
ok "Network active — IP: $IP_ADDR"
echo ""

# ── Test connectivity in stages ───────────────────────────────────────────────
info "Testing network connectivity..."

# 1. Gateway
TRIES=0
until ping -c 1 -W 2 "$GATEWAY" &>/dev/null; do
    TRIES=$((TRIES+1))
    [[ $TRIES -ge 10 ]] && error "Gateway $GATEWAY unreachable — check IP/gateway configuration"
    sleep 1
done
ok "Gateway reachable ($GATEWAY)"

# 2. Internet (no DNS)
TRIES=0
until ping -c 1 -W 2 8.8.8.8 &>/dev/null; do
    TRIES=$((TRIES+1))
    [[ $TRIES -ge 10 ]] && error "No internet connectivity — check that gateway has internet access"
    sleep 1
done
ok "Internet reachable"

# 3. DNS + HTTPS
TRIES=0
until wget -q --spider https://github.com 2>/dev/null; do
    TRIES=$((TRIES+1))
    [[ $TRIES -ge 15 ]] && error "DNS/HTTPS failed — check DNS server $DNS1"
    sleep 2
done
ok "Internet connectivity OK"
echo ""

# ── Run install.sh ────────────────────────────────────────────────────────────
info "Downloading and running HyperVision ISE Portal install.sh..."
echo ""
wget -qO- "$INSTALL_URL" | bash

# ── Mark as done ──────────────────────────────────────────────────────────────
touch "$FLAGFILE"
systemctl disable hypervision-firstboot.service 2>/dev/null || true

echo ""
echo "╔══════════════════════════════════════════════════════════════╗"
echo "║  First boot setup complete!                                  ║"
echo "╠══════════════════════════════════════════════════════════════╣"
printf "║  Portal URL: http://%-40s║\n" "$IP_ADDR:8000"
echo "╚══════════════════════════════════════════════════════════════╝"
echo ""
